/**Pannello in cui si aspetta che la
 * partita comincia
 *
 * @author gioele.zanetti
 * @version 11.11.2021
 */

package graphic;

import java.io.IOException;

public class WaitingPanel extends javax.swing.JPanel 
implements Addable{

    /**
     * Il frame che contiene tutti i pannelli
     */
    private MainFrame frame;
    
    /**
     * La lista dei giocatori
     */
    private String playerList;
    
    /**
     * Il token della partita
     */
    private String gameToken;
    
    /**
     * Crea un nuovo WaitingPanel
     * @param frame il frame che contiene i pannelli
     */
    public WaitingPanel(MainFrame frame) {
        initComponents();
        this.frame = frame;
    }
    
    /**
     * Crea un nuovo WaitingPanel
     * @param frame il frame che contiene i pannelli
     * @param gameToken il token della partita
     */
    public WaitingPanel(MainFrame frame, String gameToken) {
        initComponents();
        this.frame = frame;
        this.gameToken = gameToken;
        jTextField1.setText(this.gameToken);
    }
    
    @Override
    public void setData(Object o, String parameter) {
        if(parameter.equals("gameToken")){
            this.gameToken = (String)o;
            jTextField1.setText((String)o);
            this.frame.getClient().setGameName((String)o);
            try{
                this.frame.getClient().elaborateRequest("get players");
            }catch(IOException ioe){
                return;
            }
        }else if(parameter.equals("playerList")){
            this.playerList = (String)o;
            jTextArea1.setText((String)o);
        }else if(parameter.equals("start game")){
            this.frame.removePanel();
            this.frame.addPanel(new GamePanel(this.frame, this.playerList));
        }else if(parameter.equals("leave game")){
            this.frame.removePanel();
            this.frame.addPanel(new MainPanel(this.frame, frame.getClient().getUsername()));
        }else if(parameter.equals("adminLeft")){
            jLabel1.setText("Admin left the game, please leave the game!");
            jTextArea1.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setEditable(false);

        jButton1.setText("Inizia la partita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lascia la partita");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(20, 20, 20)
                                .addComponent(jButton2))
                            .addComponent(jLabel1))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            this.frame.getClient().elaborateRequest("start game");
        }catch(IOException ioe){
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            this.frame.getClient().elaborateRequest("leave game");
            this.frame.removePanel();
            this.frame.addPanel(new MainPanel(this.frame));
        }catch(IOException ioe){
            return;
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
